// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/services.proto

package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Appliance struct {
	ApplianceID          string   `protobuf:"bytes,1,opt,name=ApplianceID,proto3" json:"ApplianceID,omitempty"`
	ApplianceName        string   `protobuf:"bytes,2,opt,name=ApplianceName,proto3" json:"ApplianceName,omitempty"`
	DigitalControl       bool     `protobuf:"varint,3,opt,name=DigitalControl,proto3" json:"DigitalControl,omitempty"`
	AnalogueControl      bool     `protobuf:"varint,4,opt,name=AnalogueControl,proto3" json:"AnalogueControl,omitempty"`
	Temp                 bool     `protobuf:"varint,5,opt,name=Temp,proto3" json:"Temp,omitempty"`
	Color                bool     `protobuf:"varint,6,opt,name=Color,proto3" json:"Color,omitempty"`
	DigitalValue         int32    `protobuf:"varint,7,opt,name=DigitalValue,proto3" json:"DigitalValue,omitempty"`
	AnalogueValue        int32    `protobuf:"varint,8,opt,name=AnalogueValue,proto3" json:"AnalogueValue,omitempty"`
	ColorRed             int32    `protobuf:"varint,9,opt,name=ColorRed,proto3" json:"ColorRed,omitempty"`
	ColorBlue            int32    `protobuf:"varint,10,opt,name=ColorBlue,proto3" json:"ColorBlue,omitempty"`
	ColorGreen           int32    `protobuf:"varint,11,opt,name=ColorGreen,proto3" json:"ColorGreen,omitempty"`
	TempInCelcius        int32    `protobuf:"varint,12,opt,name=TempInCelcius,proto3" json:"TempInCelcius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Appliance) Reset()         { *m = Appliance{} }
func (m *Appliance) String() string { return proto.CompactTextString(m) }
func (*Appliance) ProtoMessage()    {}
func (*Appliance) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{0}
}
func (m *Appliance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Appliance.Unmarshal(m, b)
}
func (m *Appliance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Appliance.Marshal(b, m, deterministic)
}
func (dst *Appliance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Appliance.Merge(dst, src)
}
func (m *Appliance) XXX_Size() int {
	return xxx_messageInfo_Appliance.Size(m)
}
func (m *Appliance) XXX_DiscardUnknown() {
	xxx_messageInfo_Appliance.DiscardUnknown(m)
}

var xxx_messageInfo_Appliance proto.InternalMessageInfo

func (m *Appliance) GetApplianceID() string {
	if m != nil {
		return m.ApplianceID
	}
	return ""
}

func (m *Appliance) GetApplianceName() string {
	if m != nil {
		return m.ApplianceName
	}
	return ""
}

func (m *Appliance) GetDigitalControl() bool {
	if m != nil {
		return m.DigitalControl
	}
	return false
}

func (m *Appliance) GetAnalogueControl() bool {
	if m != nil {
		return m.AnalogueControl
	}
	return false
}

func (m *Appliance) GetTemp() bool {
	if m != nil {
		return m.Temp
	}
	return false
}

func (m *Appliance) GetColor() bool {
	if m != nil {
		return m.Color
	}
	return false
}

func (m *Appliance) GetDigitalValue() int32 {
	if m != nil {
		return m.DigitalValue
	}
	return 0
}

func (m *Appliance) GetAnalogueValue() int32 {
	if m != nil {
		return m.AnalogueValue
	}
	return 0
}

func (m *Appliance) GetColorRed() int32 {
	if m != nil {
		return m.ColorRed
	}
	return 0
}

func (m *Appliance) GetColorBlue() int32 {
	if m != nil {
		return m.ColorBlue
	}
	return 0
}

func (m *Appliance) GetColorGreen() int32 {
	if m != nil {
		return m.ColorGreen
	}
	return 0
}

func (m *Appliance) GetTempInCelcius() int32 {
	if m != nil {
		return m.TempInCelcius
	}
	return 0
}

type Portion struct {
	PortionID            string       `protobuf:"bytes,1,opt,name=PortionID,proto3" json:"PortionID,omitempty"`
	PortionName          string       `protobuf:"bytes,2,opt,name=PortionName,proto3" json:"PortionName,omitempty"`
	PortionLocation      string       `protobuf:"bytes,3,opt,name=PortionLocation,proto3" json:"PortionLocation,omitempty"`
	PortionImages        []string     `protobuf:"bytes,4,rep,name=PortionImages,proto3" json:"PortionImages,omitempty"`
	PortionAppliances    []*Appliance `protobuf:"bytes,5,rep,name=PortionAppliances,proto3" json:"PortionAppliances,omitempty"`
	SubPortion           []*Portion   `protobuf:"bytes,6,rep,name=SubPortion,proto3" json:"SubPortion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Portion) Reset()         { *m = Portion{} }
func (m *Portion) String() string { return proto.CompactTextString(m) }
func (*Portion) ProtoMessage()    {}
func (*Portion) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{1}
}
func (m *Portion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Portion.Unmarshal(m, b)
}
func (m *Portion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Portion.Marshal(b, m, deterministic)
}
func (dst *Portion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Portion.Merge(dst, src)
}
func (m *Portion) XXX_Size() int {
	return xxx_messageInfo_Portion.Size(m)
}
func (m *Portion) XXX_DiscardUnknown() {
	xxx_messageInfo_Portion.DiscardUnknown(m)
}

var xxx_messageInfo_Portion proto.InternalMessageInfo

func (m *Portion) GetPortionID() string {
	if m != nil {
		return m.PortionID
	}
	return ""
}

func (m *Portion) GetPortionName() string {
	if m != nil {
		return m.PortionName
	}
	return ""
}

func (m *Portion) GetPortionLocation() string {
	if m != nil {
		return m.PortionLocation
	}
	return ""
}

func (m *Portion) GetPortionImages() []string {
	if m != nil {
		return m.PortionImages
	}
	return nil
}

func (m *Portion) GetPortionAppliances() []*Appliance {
	if m != nil {
		return m.PortionAppliances
	}
	return nil
}

func (m *Portion) GetSubPortion() []*Portion {
	if m != nil {
		return m.SubPortion
	}
	return nil
}

type Room struct {
	RoomID               string       `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	RoomName             string       `protobuf:"bytes,2,opt,name=RoomName,proto3" json:"RoomName,omitempty"`
	RoomLocation         string       `protobuf:"bytes,3,opt,name=RoomLocation,proto3" json:"RoomLocation,omitempty"`
	RoomImages           []string     `protobuf:"bytes,4,rep,name=RoomImages,proto3" json:"RoomImages,omitempty"`
	RoomAppliances       []*Appliance `protobuf:"bytes,5,rep,name=RoomAppliances,proto3" json:"RoomAppliances,omitempty"`
	SubRooms             []*Room      `protobuf:"bytes,6,rep,name=SubRooms,proto3" json:"SubRooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{2}
}
func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (dst *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(dst, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *Room) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *Room) GetRoomLocation() string {
	if m != nil {
		return m.RoomLocation
	}
	return ""
}

func (m *Room) GetRoomImages() []string {
	if m != nil {
		return m.RoomImages
	}
	return nil
}

func (m *Room) GetRoomAppliances() []*Appliance {
	if m != nil {
		return m.RoomAppliances
	}
	return nil
}

func (m *Room) GetSubRooms() []*Room {
	if m != nil {
		return m.SubRooms
	}
	return nil
}

type Place struct {
	PlaceID              string   `protobuf:"bytes,1,opt,name=PlaceID,proto3" json:"PlaceID,omitempty"`
	PlaceName            string   `protobuf:"bytes,2,opt,name=PlaceName,proto3" json:"PlaceName,omitempty"`
	PlaceAddress         string   `protobuf:"bytes,3,opt,name=PlaceAddress,proto3" json:"PlaceAddress,omitempty"`
	PlaceImages          []string `protobuf:"bytes,4,rep,name=PlaceImages,proto3" json:"PlaceImages,omitempty"`
	PlaceRooms           []*Room  `protobuf:"bytes,5,rep,name=PlaceRooms,proto3" json:"PlaceRooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Place) Reset()         { *m = Place{} }
func (m *Place) String() string { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()    {}
func (*Place) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{3}
}
func (m *Place) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Place.Unmarshal(m, b)
}
func (m *Place) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Place.Marshal(b, m, deterministic)
}
func (dst *Place) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Place.Merge(dst, src)
}
func (m *Place) XXX_Size() int {
	return xxx_messageInfo_Place.Size(m)
}
func (m *Place) XXX_DiscardUnknown() {
	xxx_messageInfo_Place.DiscardUnknown(m)
}

var xxx_messageInfo_Place proto.InternalMessageInfo

func (m *Place) GetPlaceID() string {
	if m != nil {
		return m.PlaceID
	}
	return ""
}

func (m *Place) GetPlaceName() string {
	if m != nil {
		return m.PlaceName
	}
	return ""
}

func (m *Place) GetPlaceAddress() string {
	if m != nil {
		return m.PlaceAddress
	}
	return ""
}

func (m *Place) GetPlaceImages() []string {
	if m != nil {
		return m.PlaceImages
	}
	return nil
}

func (m *Place) GetPlaceRooms() []*Room {
	if m != nil {
		return m.PlaceRooms
	}
	return nil
}

type Client struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	ClientName           string   `protobuf:"bytes,2,opt,name=ClientName,proto3" json:"ClientName,omitempty"`
	ClientAddress        string   `protobuf:"bytes,3,opt,name=ClientAddress,proto3" json:"ClientAddress,omitempty"`
	ClientContact        int64    `protobuf:"varint,4,opt,name=ClientContact,proto3" json:"ClientContact,omitempty"`
	ClientEmail          string   `protobuf:"bytes,5,opt,name=ClientEmail,proto3" json:"ClientEmail,omitempty"`
	ClientPlaces         []*Place `protobuf:"bytes,6,rep,name=ClientPlaces,proto3" json:"ClientPlaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{4}
}
func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (dst *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(dst, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *Client) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func (m *Client) GetClientAddress() string {
	if m != nil {
		return m.ClientAddress
	}
	return ""
}

func (m *Client) GetClientContact() int64 {
	if m != nil {
		return m.ClientContact
	}
	return 0
}

func (m *Client) GetClientEmail() string {
	if m != nil {
		return m.ClientEmail
	}
	return ""
}

func (m *Client) GetClientPlaces() []*Place {
	if m != nil {
		return m.ClientPlaces
	}
	return nil
}

type CreateClientRequest struct {
	Client               *Client  `protobuf:"bytes,1,opt,name=Client,proto3" json:"Client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientRequest) Reset()         { *m = CreateClientRequest{} }
func (m *CreateClientRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClientRequest) ProtoMessage()    {}
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{5}
}
func (m *CreateClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientRequest.Unmarshal(m, b)
}
func (m *CreateClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientRequest.Marshal(b, m, deterministic)
}
func (dst *CreateClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientRequest.Merge(dst, src)
}
func (m *CreateClientRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClientRequest.Size(m)
}
func (m *CreateClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientRequest proto.InternalMessageInfo

func (m *CreateClientRequest) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

type CreateClientResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Client               *Client  `protobuf:"bytes,2,opt,name=Client,proto3" json:"Client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientResponse) Reset()         { *m = CreateClientResponse{} }
func (m *CreateClientResponse) String() string { return proto.CompactTextString(m) }
func (*CreateClientResponse) ProtoMessage()    {}
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{6}
}
func (m *CreateClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientResponse.Unmarshal(m, b)
}
func (m *CreateClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientResponse.Marshal(b, m, deterministic)
}
func (dst *CreateClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientResponse.Merge(dst, src)
}
func (m *CreateClientResponse) XXX_Size() int {
	return xxx_messageInfo_CreateClientResponse.Size(m)
}
func (m *CreateClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientResponse proto.InternalMessageInfo

func (m *CreateClientResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateClientResponse) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

type Command struct {
	Value                int32    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	ColorRGB             []int32  `protobuf:"varint,2,rep,packed,name=ColorRGB,proto3" json:"ColorRGB,omitempty"`
	Temp                 int32    `protobuf:"varint,3,opt,name=Temp,proto3" json:"Temp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{7}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Command) GetColorRGB() []int32 {
	if m != nil {
		return m.ColorRGB
	}
	return nil
}

func (m *Command) GetTemp() int32 {
	if m != nil {
		return m.Temp
	}
	return 0
}

type ControlApplianceRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	ApplianceID          string   `protobuf:"bytes,2,opt,name=ApplianceID,proto3" json:"ApplianceID,omitempty"`
	Command              *Command `protobuf:"bytes,3,opt,name=Command,proto3" json:"Command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlApplianceRequest) Reset()         { *m = ControlApplianceRequest{} }
func (m *ControlApplianceRequest) String() string { return proto.CompactTextString(m) }
func (*ControlApplianceRequest) ProtoMessage()    {}
func (*ControlApplianceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{8}
}
func (m *ControlApplianceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlApplianceRequest.Unmarshal(m, b)
}
func (m *ControlApplianceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlApplianceRequest.Marshal(b, m, deterministic)
}
func (dst *ControlApplianceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlApplianceRequest.Merge(dst, src)
}
func (m *ControlApplianceRequest) XXX_Size() int {
	return xxx_messageInfo_ControlApplianceRequest.Size(m)
}
func (m *ControlApplianceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlApplianceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ControlApplianceRequest proto.InternalMessageInfo

func (m *ControlApplianceRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *ControlApplianceRequest) GetApplianceID() string {
	if m != nil {
		return m.ApplianceID
	}
	return ""
}

func (m *ControlApplianceRequest) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type ControlApplianceResponse struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	ApplianceID          string   `protobuf:"bytes,2,opt,name=ApplianceID,proto3" json:"ApplianceID,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=Success,proto3" json:"Success,omitempty"`
	Result               *Command `protobuf:"bytes,4,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlApplianceResponse) Reset()         { *m = ControlApplianceResponse{} }
func (m *ControlApplianceResponse) String() string { return proto.CompactTextString(m) }
func (*ControlApplianceResponse) ProtoMessage()    {}
func (*ControlApplianceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{9}
}
func (m *ControlApplianceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlApplianceResponse.Unmarshal(m, b)
}
func (m *ControlApplianceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlApplianceResponse.Marshal(b, m, deterministic)
}
func (dst *ControlApplianceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlApplianceResponse.Merge(dst, src)
}
func (m *ControlApplianceResponse) XXX_Size() int {
	return xxx_messageInfo_ControlApplianceResponse.Size(m)
}
func (m *ControlApplianceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlApplianceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ControlApplianceResponse proto.InternalMessageInfo

func (m *ControlApplianceResponse) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *ControlApplianceResponse) GetApplianceID() string {
	if m != nil {
		return m.ApplianceID
	}
	return ""
}

func (m *ControlApplianceResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ControlApplianceResponse) GetResult() *Command {
	if m != nil {
		return m.Result
	}
	return nil
}

type EditClientRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	NewClient            *Client  `protobuf:"bytes,2,opt,name=NewClient,proto3" json:"NewClient,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditClientRequest) Reset()         { *m = EditClientRequest{} }
func (m *EditClientRequest) String() string { return proto.CompactTextString(m) }
func (*EditClientRequest) ProtoMessage()    {}
func (*EditClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{10}
}
func (m *EditClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditClientRequest.Unmarshal(m, b)
}
func (m *EditClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditClientRequest.Marshal(b, m, deterministic)
}
func (dst *EditClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditClientRequest.Merge(dst, src)
}
func (m *EditClientRequest) XXX_Size() int {
	return xxx_messageInfo_EditClientRequest.Size(m)
}
func (m *EditClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditClientRequest proto.InternalMessageInfo

func (m *EditClientRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *EditClientRequest) GetNewClient() *Client {
	if m != nil {
		return m.NewClient
	}
	return nil
}

type EditClientResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditClientResponse) Reset()         { *m = EditClientResponse{} }
func (m *EditClientResponse) String() string { return proto.CompactTextString(m) }
func (*EditClientResponse) ProtoMessage()    {}
func (*EditClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{11}
}
func (m *EditClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditClientResponse.Unmarshal(m, b)
}
func (m *EditClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditClientResponse.Marshal(b, m, deterministic)
}
func (dst *EditClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditClientResponse.Merge(dst, src)
}
func (m *EditClientResponse) XXX_Size() int {
	return xxx_messageInfo_EditClientResponse.Size(m)
}
func (m *EditClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditClientResponse proto.InternalMessageInfo

func (m *EditClientResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AddClientPlaceRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Place                *Place   `protobuf:"bytes,2,opt,name=Place,proto3" json:"Place,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddClientPlaceRequest) Reset()         { *m = AddClientPlaceRequest{} }
func (m *AddClientPlaceRequest) String() string { return proto.CompactTextString(m) }
func (*AddClientPlaceRequest) ProtoMessage()    {}
func (*AddClientPlaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{12}
}
func (m *AddClientPlaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClientPlaceRequest.Unmarshal(m, b)
}
func (m *AddClientPlaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClientPlaceRequest.Marshal(b, m, deterministic)
}
func (dst *AddClientPlaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClientPlaceRequest.Merge(dst, src)
}
func (m *AddClientPlaceRequest) XXX_Size() int {
	return xxx_messageInfo_AddClientPlaceRequest.Size(m)
}
func (m *AddClientPlaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClientPlaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddClientPlaceRequest proto.InternalMessageInfo

func (m *AddClientPlaceRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *AddClientPlaceRequest) GetPlace() *Place {
	if m != nil {
		return m.Place
	}
	return nil
}

type AddClientPlaceResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddClientPlaceResponse) Reset()         { *m = AddClientPlaceResponse{} }
func (m *AddClientPlaceResponse) String() string { return proto.CompactTextString(m) }
func (*AddClientPlaceResponse) ProtoMessage()    {}
func (*AddClientPlaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{13}
}
func (m *AddClientPlaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClientPlaceResponse.Unmarshal(m, b)
}
func (m *AddClientPlaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClientPlaceResponse.Marshal(b, m, deterministic)
}
func (dst *AddClientPlaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClientPlaceResponse.Merge(dst, src)
}
func (m *AddClientPlaceResponse) XXX_Size() int {
	return xxx_messageInfo_AddClientPlaceResponse.Size(m)
}
func (m *AddClientPlaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClientPlaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddClientPlaceResponse proto.InternalMessageInfo

func (m *AddClientPlaceResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type EditClientPlaceRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	PlaceID              string   `protobuf:"bytes,2,opt,name=PlaceID,proto3" json:"PlaceID,omitempty"`
	NewPlace             *Place   `protobuf:"bytes,3,opt,name=NewPlace,proto3" json:"NewPlace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditClientPlaceRequest) Reset()         { *m = EditClientPlaceRequest{} }
func (m *EditClientPlaceRequest) String() string { return proto.CompactTextString(m) }
func (*EditClientPlaceRequest) ProtoMessage()    {}
func (*EditClientPlaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{14}
}
func (m *EditClientPlaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditClientPlaceRequest.Unmarshal(m, b)
}
func (m *EditClientPlaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditClientPlaceRequest.Marshal(b, m, deterministic)
}
func (dst *EditClientPlaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditClientPlaceRequest.Merge(dst, src)
}
func (m *EditClientPlaceRequest) XXX_Size() int {
	return xxx_messageInfo_EditClientPlaceRequest.Size(m)
}
func (m *EditClientPlaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditClientPlaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditClientPlaceRequest proto.InternalMessageInfo

func (m *EditClientPlaceRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *EditClientPlaceRequest) GetPlaceID() string {
	if m != nil {
		return m.PlaceID
	}
	return ""
}

func (m *EditClientPlaceRequest) GetNewPlace() *Place {
	if m != nil {
		return m.NewPlace
	}
	return nil
}

type EditClientPlaceResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditClientPlaceResponse) Reset()         { *m = EditClientPlaceResponse{} }
func (m *EditClientPlaceResponse) String() string { return proto.CompactTextString(m) }
func (*EditClientPlaceResponse) ProtoMessage()    {}
func (*EditClientPlaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{15}
}
func (m *EditClientPlaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditClientPlaceResponse.Unmarshal(m, b)
}
func (m *EditClientPlaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditClientPlaceResponse.Marshal(b, m, deterministic)
}
func (dst *EditClientPlaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditClientPlaceResponse.Merge(dst, src)
}
func (m *EditClientPlaceResponse) XXX_Size() int {
	return xxx_messageInfo_EditClientPlaceResponse.Size(m)
}
func (m *EditClientPlaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditClientPlaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditClientPlaceResponse proto.InternalMessageInfo

func (m *EditClientPlaceResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AddClientRoomRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	PlaceID              string   `protobuf:"bytes,2,opt,name=PlaceID,proto3" json:"PlaceID,omitempty"`
	Room                 *Room    `protobuf:"bytes,3,opt,name=Room,proto3" json:"Room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddClientRoomRequest) Reset()         { *m = AddClientRoomRequest{} }
func (m *AddClientRoomRequest) String() string { return proto.CompactTextString(m) }
func (*AddClientRoomRequest) ProtoMessage()    {}
func (*AddClientRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{16}
}
func (m *AddClientRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClientRoomRequest.Unmarshal(m, b)
}
func (m *AddClientRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClientRoomRequest.Marshal(b, m, deterministic)
}
func (dst *AddClientRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClientRoomRequest.Merge(dst, src)
}
func (m *AddClientRoomRequest) XXX_Size() int {
	return xxx_messageInfo_AddClientRoomRequest.Size(m)
}
func (m *AddClientRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClientRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddClientRoomRequest proto.InternalMessageInfo

func (m *AddClientRoomRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *AddClientRoomRequest) GetPlaceID() string {
	if m != nil {
		return m.PlaceID
	}
	return ""
}

func (m *AddClientRoomRequest) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type AddClientRoomResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddClientRoomResponse) Reset()         { *m = AddClientRoomResponse{} }
func (m *AddClientRoomResponse) String() string { return proto.CompactTextString(m) }
func (*AddClientRoomResponse) ProtoMessage()    {}
func (*AddClientRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{17}
}
func (m *AddClientRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClientRoomResponse.Unmarshal(m, b)
}
func (m *AddClientRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClientRoomResponse.Marshal(b, m, deterministic)
}
func (dst *AddClientRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClientRoomResponse.Merge(dst, src)
}
func (m *AddClientRoomResponse) XXX_Size() int {
	return xxx_messageInfo_AddClientRoomResponse.Size(m)
}
func (m *AddClientRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClientRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddClientRoomResponse proto.InternalMessageInfo

func (m *AddClientRoomResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type EditClientRoomRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	PlaceID              string   `protobuf:"bytes,2,opt,name=PlaceID,proto3" json:"PlaceID,omitempty"`
	RoomID               string   `protobuf:"bytes,3,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	NewRoom              *Room    `protobuf:"bytes,4,opt,name=NewRoom,proto3" json:"NewRoom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditClientRoomRequest) Reset()         { *m = EditClientRoomRequest{} }
func (m *EditClientRoomRequest) String() string { return proto.CompactTextString(m) }
func (*EditClientRoomRequest) ProtoMessage()    {}
func (*EditClientRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{18}
}
func (m *EditClientRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditClientRoomRequest.Unmarshal(m, b)
}
func (m *EditClientRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditClientRoomRequest.Marshal(b, m, deterministic)
}
func (dst *EditClientRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditClientRoomRequest.Merge(dst, src)
}
func (m *EditClientRoomRequest) XXX_Size() int {
	return xxx_messageInfo_EditClientRoomRequest.Size(m)
}
func (m *EditClientRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditClientRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditClientRoomRequest proto.InternalMessageInfo

func (m *EditClientRoomRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *EditClientRoomRequest) GetPlaceID() string {
	if m != nil {
		return m.PlaceID
	}
	return ""
}

func (m *EditClientRoomRequest) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *EditClientRoomRequest) GetNewRoom() *Room {
	if m != nil {
		return m.NewRoom
	}
	return nil
}

type EditClientRoomResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditClientRoomResponse) Reset()         { *m = EditClientRoomResponse{} }
func (m *EditClientRoomResponse) String() string { return proto.CompactTextString(m) }
func (*EditClientRoomResponse) ProtoMessage()    {}
func (*EditClientRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{19}
}
func (m *EditClientRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditClientRoomResponse.Unmarshal(m, b)
}
func (m *EditClientRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditClientRoomResponse.Marshal(b, m, deterministic)
}
func (dst *EditClientRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditClientRoomResponse.Merge(dst, src)
}
func (m *EditClientRoomResponse) XXX_Size() int {
	return xxx_messageInfo_EditClientRoomResponse.Size(m)
}
func (m *EditClientRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditClientRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditClientRoomResponse proto.InternalMessageInfo

func (m *EditClientRoomResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AddClientApplianceRequest struct {
	ClientID             string     `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	PlaceID              string     `protobuf:"bytes,2,opt,name=PlaceID,proto3" json:"PlaceID,omitempty"`
	RoomID               string     `protobuf:"bytes,3,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Appliance            *Appliance `protobuf:"bytes,4,opt,name=Appliance,proto3" json:"Appliance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddClientApplianceRequest) Reset()         { *m = AddClientApplianceRequest{} }
func (m *AddClientApplianceRequest) String() string { return proto.CompactTextString(m) }
func (*AddClientApplianceRequest) ProtoMessage()    {}
func (*AddClientApplianceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{20}
}
func (m *AddClientApplianceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClientApplianceRequest.Unmarshal(m, b)
}
func (m *AddClientApplianceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClientApplianceRequest.Marshal(b, m, deterministic)
}
func (dst *AddClientApplianceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClientApplianceRequest.Merge(dst, src)
}
func (m *AddClientApplianceRequest) XXX_Size() int {
	return xxx_messageInfo_AddClientApplianceRequest.Size(m)
}
func (m *AddClientApplianceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClientApplianceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddClientApplianceRequest proto.InternalMessageInfo

func (m *AddClientApplianceRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *AddClientApplianceRequest) GetPlaceID() string {
	if m != nil {
		return m.PlaceID
	}
	return ""
}

func (m *AddClientApplianceRequest) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *AddClientApplianceRequest) GetAppliance() *Appliance {
	if m != nil {
		return m.Appliance
	}
	return nil
}

type AddClientApplianceResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddClientApplianceResponse) Reset()         { *m = AddClientApplianceResponse{} }
func (m *AddClientApplianceResponse) String() string { return proto.CompactTextString(m) }
func (*AddClientApplianceResponse) ProtoMessage()    {}
func (*AddClientApplianceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{21}
}
func (m *AddClientApplianceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClientApplianceResponse.Unmarshal(m, b)
}
func (m *AddClientApplianceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClientApplianceResponse.Marshal(b, m, deterministic)
}
func (dst *AddClientApplianceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClientApplianceResponse.Merge(dst, src)
}
func (m *AddClientApplianceResponse) XXX_Size() int {
	return xxx_messageInfo_AddClientApplianceResponse.Size(m)
}
func (m *AddClientApplianceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClientApplianceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddClientApplianceResponse proto.InternalMessageInfo

func (m *AddClientApplianceResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type EditClientApplianceRequest struct {
	ClientID             string     `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	PlaceID              string     `protobuf:"bytes,2,opt,name=PlaceID,proto3" json:"PlaceID,omitempty"`
	RoomID               string     `protobuf:"bytes,3,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	ApplianceID          string     `protobuf:"bytes,4,opt,name=ApplianceID,proto3" json:"ApplianceID,omitempty"`
	NewAppliance         *Appliance `protobuf:"bytes,5,opt,name=NewAppliance,proto3" json:"NewAppliance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EditClientApplianceRequest) Reset()         { *m = EditClientApplianceRequest{} }
func (m *EditClientApplianceRequest) String() string { return proto.CompactTextString(m) }
func (*EditClientApplianceRequest) ProtoMessage()    {}
func (*EditClientApplianceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{22}
}
func (m *EditClientApplianceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditClientApplianceRequest.Unmarshal(m, b)
}
func (m *EditClientApplianceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditClientApplianceRequest.Marshal(b, m, deterministic)
}
func (dst *EditClientApplianceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditClientApplianceRequest.Merge(dst, src)
}
func (m *EditClientApplianceRequest) XXX_Size() int {
	return xxx_messageInfo_EditClientApplianceRequest.Size(m)
}
func (m *EditClientApplianceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditClientApplianceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditClientApplianceRequest proto.InternalMessageInfo

func (m *EditClientApplianceRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *EditClientApplianceRequest) GetPlaceID() string {
	if m != nil {
		return m.PlaceID
	}
	return ""
}

func (m *EditClientApplianceRequest) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *EditClientApplianceRequest) GetApplianceID() string {
	if m != nil {
		return m.ApplianceID
	}
	return ""
}

func (m *EditClientApplianceRequest) GetNewAppliance() *Appliance {
	if m != nil {
		return m.NewAppliance
	}
	return nil
}

type EditClientApplianceResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditClientApplianceResponse) Reset()         { *m = EditClientApplianceResponse{} }
func (m *EditClientApplianceResponse) String() string { return proto.CompactTextString(m) }
func (*EditClientApplianceResponse) ProtoMessage()    {}
func (*EditClientApplianceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{23}
}
func (m *EditClientApplianceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditClientApplianceResponse.Unmarshal(m, b)
}
func (m *EditClientApplianceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditClientApplianceResponse.Marshal(b, m, deterministic)
}
func (dst *EditClientApplianceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditClientApplianceResponse.Merge(dst, src)
}
func (m *EditClientApplianceResponse) XXX_Size() int {
	return xxx_messageInfo_EditClientApplianceResponse.Size(m)
}
func (m *EditClientApplianceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditClientApplianceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditClientApplianceResponse proto.InternalMessageInfo

func (m *EditClientApplianceResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AddClientPortionRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	PlaceID              string   `protobuf:"bytes,2,opt,name=PlaceID,proto3" json:"PlaceID,omitempty"`
	Portion              *Portion `protobuf:"bytes,3,opt,name=Portion,proto3" json:"Portion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddClientPortionRequest) Reset()         { *m = AddClientPortionRequest{} }
func (m *AddClientPortionRequest) String() string { return proto.CompactTextString(m) }
func (*AddClientPortionRequest) ProtoMessage()    {}
func (*AddClientPortionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{24}
}
func (m *AddClientPortionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClientPortionRequest.Unmarshal(m, b)
}
func (m *AddClientPortionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClientPortionRequest.Marshal(b, m, deterministic)
}
func (dst *AddClientPortionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClientPortionRequest.Merge(dst, src)
}
func (m *AddClientPortionRequest) XXX_Size() int {
	return xxx_messageInfo_AddClientPortionRequest.Size(m)
}
func (m *AddClientPortionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClientPortionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddClientPortionRequest proto.InternalMessageInfo

func (m *AddClientPortionRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *AddClientPortionRequest) GetPlaceID() string {
	if m != nil {
		return m.PlaceID
	}
	return ""
}

func (m *AddClientPortionRequest) GetPortion() *Portion {
	if m != nil {
		return m.Portion
	}
	return nil
}

type AddClientPortionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddClientPortionResponse) Reset()         { *m = AddClientPortionResponse{} }
func (m *AddClientPortionResponse) String() string { return proto.CompactTextString(m) }
func (*AddClientPortionResponse) ProtoMessage()    {}
func (*AddClientPortionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{25}
}
func (m *AddClientPortionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClientPortionResponse.Unmarshal(m, b)
}
func (m *AddClientPortionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClientPortionResponse.Marshal(b, m, deterministic)
}
func (dst *AddClientPortionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClientPortionResponse.Merge(dst, src)
}
func (m *AddClientPortionResponse) XXX_Size() int {
	return xxx_messageInfo_AddClientPortionResponse.Size(m)
}
func (m *AddClientPortionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClientPortionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddClientPortionResponse proto.InternalMessageInfo

func (m *AddClientPortionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type EditClientPortionRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	PlaceID              string   `protobuf:"bytes,2,opt,name=PlaceID,proto3" json:"PlaceID,omitempty"`
	PortionID            string   `protobuf:"bytes,3,opt,name=PortionID,proto3" json:"PortionID,omitempty"`
	NewPortion           *Portion `protobuf:"bytes,4,opt,name=NewPortion,proto3" json:"NewPortion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditClientPortionRequest) Reset()         { *m = EditClientPortionRequest{} }
func (m *EditClientPortionRequest) String() string { return proto.CompactTextString(m) }
func (*EditClientPortionRequest) ProtoMessage()    {}
func (*EditClientPortionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{26}
}
func (m *EditClientPortionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditClientPortionRequest.Unmarshal(m, b)
}
func (m *EditClientPortionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditClientPortionRequest.Marshal(b, m, deterministic)
}
func (dst *EditClientPortionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditClientPortionRequest.Merge(dst, src)
}
func (m *EditClientPortionRequest) XXX_Size() int {
	return xxx_messageInfo_EditClientPortionRequest.Size(m)
}
func (m *EditClientPortionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditClientPortionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditClientPortionRequest proto.InternalMessageInfo

func (m *EditClientPortionRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *EditClientPortionRequest) GetPlaceID() string {
	if m != nil {
		return m.PlaceID
	}
	return ""
}

func (m *EditClientPortionRequest) GetPortionID() string {
	if m != nil {
		return m.PortionID
	}
	return ""
}

func (m *EditClientPortionRequest) GetNewPortion() *Portion {
	if m != nil {
		return m.NewPortion
	}
	return nil
}

type EditClientPortionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditClientPortionResponse) Reset()         { *m = EditClientPortionResponse{} }
func (m *EditClientPortionResponse) String() string { return proto.CompactTextString(m) }
func (*EditClientPortionResponse) ProtoMessage()    {}
func (*EditClientPortionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_services_6f6bc4c5b9569fc9, []int{27}
}
func (m *EditClientPortionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditClientPortionResponse.Unmarshal(m, b)
}
func (m *EditClientPortionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditClientPortionResponse.Marshal(b, m, deterministic)
}
func (dst *EditClientPortionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditClientPortionResponse.Merge(dst, src)
}
func (m *EditClientPortionResponse) XXX_Size() int {
	return xxx_messageInfo_EditClientPortionResponse.Size(m)
}
func (m *EditClientPortionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditClientPortionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditClientPortionResponse proto.InternalMessageInfo

func (m *EditClientPortionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Appliance)(nil), "services.Appliance")
	proto.RegisterType((*Portion)(nil), "services.Portion")
	proto.RegisterType((*Room)(nil), "services.Room")
	proto.RegisterType((*Place)(nil), "services.Place")
	proto.RegisterType((*Client)(nil), "services.Client")
	proto.RegisterType((*CreateClientRequest)(nil), "services.CreateClientRequest")
	proto.RegisterType((*CreateClientResponse)(nil), "services.CreateClientResponse")
	proto.RegisterType((*Command)(nil), "services.Command")
	proto.RegisterType((*ControlApplianceRequest)(nil), "services.ControlApplianceRequest")
	proto.RegisterType((*ControlApplianceResponse)(nil), "services.ControlApplianceResponse")
	proto.RegisterType((*EditClientRequest)(nil), "services.EditClientRequest")
	proto.RegisterType((*EditClientResponse)(nil), "services.EditClientResponse")
	proto.RegisterType((*AddClientPlaceRequest)(nil), "services.AddClientPlaceRequest")
	proto.RegisterType((*AddClientPlaceResponse)(nil), "services.AddClientPlaceResponse")
	proto.RegisterType((*EditClientPlaceRequest)(nil), "services.EditClientPlaceRequest")
	proto.RegisterType((*EditClientPlaceResponse)(nil), "services.EditClientPlaceResponse")
	proto.RegisterType((*AddClientRoomRequest)(nil), "services.AddClientRoomRequest")
	proto.RegisterType((*AddClientRoomResponse)(nil), "services.AddClientRoomResponse")
	proto.RegisterType((*EditClientRoomRequest)(nil), "services.EditClientRoomRequest")
	proto.RegisterType((*EditClientRoomResponse)(nil), "services.EditClientRoomResponse")
	proto.RegisterType((*AddClientApplianceRequest)(nil), "services.AddClientApplianceRequest")
	proto.RegisterType((*AddClientApplianceResponse)(nil), "services.AddClientApplianceResponse")
	proto.RegisterType((*EditClientApplianceRequest)(nil), "services.EditClientApplianceRequest")
	proto.RegisterType((*EditClientApplianceResponse)(nil), "services.EditClientApplianceResponse")
	proto.RegisterType((*AddClientPortionRequest)(nil), "services.AddClientPortionRequest")
	proto.RegisterType((*AddClientPortionResponse)(nil), "services.AddClientPortionResponse")
	proto.RegisterType((*EditClientPortionRequest)(nil), "services.EditClientPortionRequest")
	proto.RegisterType((*EditClientPortionResponse)(nil), "services.EditClientPortionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlHomeClient is the client API for ControlHome service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlHomeClient interface {
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	EditClient(ctx context.Context, in *EditClientRequest, opts ...grpc.CallOption) (*EditClientResponse, error)
	AddClientPlace(ctx context.Context, in *AddClientPlaceRequest, opts ...grpc.CallOption) (*AddClientPlaceResponse, error)
	EditClientPlace(ctx context.Context, in *EditClientPlaceRequest, opts ...grpc.CallOption) (*EditClientPlaceResponse, error)
	AddClientRoom(ctx context.Context, in *AddClientRoomRequest, opts ...grpc.CallOption) (*AddClientRoomResponse, error)
	EditClientRoom(ctx context.Context, in *EditClientRoomRequest, opts ...grpc.CallOption) (*EditClientRoomResponse, error)
	AddClientPortion(ctx context.Context, in *AddClientPortionRequest, opts ...grpc.CallOption) (*AddClientPortionResponse, error)
	EditClientPortion(ctx context.Context, in *EditClientPortionRequest, opts ...grpc.CallOption) (*EditClientPortionResponse, error)
	AddClientAppliance(ctx context.Context, in *AddClientApplianceRequest, opts ...grpc.CallOption) (*AddClientApplianceResponse, error)
	EditClientAppliance(ctx context.Context, in *EditClientApplianceRequest, opts ...grpc.CallOption) (*EditClientApplianceResponse, error)
	ControlAppliance(ctx context.Context, in *ControlApplianceRequest, opts ...grpc.CallOption) (*ControlApplianceResponse, error)
}

type controlHomeClient struct {
	cc *grpc.ClientConn
}

func NewControlHomeClient(cc *grpc.ClientConn) ControlHomeClient {
	return &controlHomeClient{cc}
}

func (c *controlHomeClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, "/services.ControlHome/CreateClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlHomeClient) EditClient(ctx context.Context, in *EditClientRequest, opts ...grpc.CallOption) (*EditClientResponse, error) {
	out := new(EditClientResponse)
	err := c.cc.Invoke(ctx, "/services.ControlHome/EditClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlHomeClient) AddClientPlace(ctx context.Context, in *AddClientPlaceRequest, opts ...grpc.CallOption) (*AddClientPlaceResponse, error) {
	out := new(AddClientPlaceResponse)
	err := c.cc.Invoke(ctx, "/services.ControlHome/AddClientPlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlHomeClient) EditClientPlace(ctx context.Context, in *EditClientPlaceRequest, opts ...grpc.CallOption) (*EditClientPlaceResponse, error) {
	out := new(EditClientPlaceResponse)
	err := c.cc.Invoke(ctx, "/services.ControlHome/EditClientPlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlHomeClient) AddClientRoom(ctx context.Context, in *AddClientRoomRequest, opts ...grpc.CallOption) (*AddClientRoomResponse, error) {
	out := new(AddClientRoomResponse)
	err := c.cc.Invoke(ctx, "/services.ControlHome/AddClientRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlHomeClient) EditClientRoom(ctx context.Context, in *EditClientRoomRequest, opts ...grpc.CallOption) (*EditClientRoomResponse, error) {
	out := new(EditClientRoomResponse)
	err := c.cc.Invoke(ctx, "/services.ControlHome/EditClientRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlHomeClient) AddClientPortion(ctx context.Context, in *AddClientPortionRequest, opts ...grpc.CallOption) (*AddClientPortionResponse, error) {
	out := new(AddClientPortionResponse)
	err := c.cc.Invoke(ctx, "/services.ControlHome/AddClientPortion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlHomeClient) EditClientPortion(ctx context.Context, in *EditClientPortionRequest, opts ...grpc.CallOption) (*EditClientPortionResponse, error) {
	out := new(EditClientPortionResponse)
	err := c.cc.Invoke(ctx, "/services.ControlHome/EditClientPortion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlHomeClient) AddClientAppliance(ctx context.Context, in *AddClientApplianceRequest, opts ...grpc.CallOption) (*AddClientApplianceResponse, error) {
	out := new(AddClientApplianceResponse)
	err := c.cc.Invoke(ctx, "/services.ControlHome/AddClientAppliance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlHomeClient) EditClientAppliance(ctx context.Context, in *EditClientApplianceRequest, opts ...grpc.CallOption) (*EditClientApplianceResponse, error) {
	out := new(EditClientApplianceResponse)
	err := c.cc.Invoke(ctx, "/services.ControlHome/EditClientAppliance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlHomeClient) ControlAppliance(ctx context.Context, in *ControlApplianceRequest, opts ...grpc.CallOption) (*ControlApplianceResponse, error) {
	out := new(ControlApplianceResponse)
	err := c.cc.Invoke(ctx, "/services.ControlHome/ControlAppliance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlHomeServer is the server API for ControlHome service.
type ControlHomeServer interface {
	CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	EditClient(context.Context, *EditClientRequest) (*EditClientResponse, error)
	AddClientPlace(context.Context, *AddClientPlaceRequest) (*AddClientPlaceResponse, error)
	EditClientPlace(context.Context, *EditClientPlaceRequest) (*EditClientPlaceResponse, error)
	AddClientRoom(context.Context, *AddClientRoomRequest) (*AddClientRoomResponse, error)
	EditClientRoom(context.Context, *EditClientRoomRequest) (*EditClientRoomResponse, error)
	AddClientPortion(context.Context, *AddClientPortionRequest) (*AddClientPortionResponse, error)
	EditClientPortion(context.Context, *EditClientPortionRequest) (*EditClientPortionResponse, error)
	AddClientAppliance(context.Context, *AddClientApplianceRequest) (*AddClientApplianceResponse, error)
	EditClientAppliance(context.Context, *EditClientApplianceRequest) (*EditClientApplianceResponse, error)
	ControlAppliance(context.Context, *ControlApplianceRequest) (*ControlApplianceResponse, error)
}

func RegisterControlHomeServer(s *grpc.Server, srv ControlHomeServer) {
	s.RegisterService(&_ControlHome_serviceDesc, srv)
}

func _ControlHome_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlHomeServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ControlHome/CreateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlHomeServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlHome_EditClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlHomeServer).EditClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ControlHome/EditClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlHomeServer).EditClient(ctx, req.(*EditClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlHome_AddClientPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddClientPlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlHomeServer).AddClientPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ControlHome/AddClientPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlHomeServer).AddClientPlace(ctx, req.(*AddClientPlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlHome_EditClientPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditClientPlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlHomeServer).EditClientPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ControlHome/EditClientPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlHomeServer).EditClientPlace(ctx, req.(*EditClientPlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlHome_AddClientRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddClientRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlHomeServer).AddClientRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ControlHome/AddClientRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlHomeServer).AddClientRoom(ctx, req.(*AddClientRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlHome_EditClientRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditClientRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlHomeServer).EditClientRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ControlHome/EditClientRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlHomeServer).EditClientRoom(ctx, req.(*EditClientRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlHome_AddClientPortion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddClientPortionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlHomeServer).AddClientPortion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ControlHome/AddClientPortion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlHomeServer).AddClientPortion(ctx, req.(*AddClientPortionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlHome_EditClientPortion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditClientPortionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlHomeServer).EditClientPortion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ControlHome/EditClientPortion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlHomeServer).EditClientPortion(ctx, req.(*EditClientPortionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlHome_AddClientAppliance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddClientApplianceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlHomeServer).AddClientAppliance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ControlHome/AddClientAppliance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlHomeServer).AddClientAppliance(ctx, req.(*AddClientApplianceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlHome_EditClientAppliance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditClientApplianceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlHomeServer).EditClientAppliance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ControlHome/EditClientAppliance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlHomeServer).EditClientAppliance(ctx, req.(*EditClientApplianceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlHome_ControlAppliance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlApplianceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlHomeServer).ControlAppliance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ControlHome/ControlAppliance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlHomeServer).ControlAppliance(ctx, req.(*ControlApplianceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControlHome_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.ControlHome",
	HandlerType: (*ControlHomeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _ControlHome_CreateClient_Handler,
		},
		{
			MethodName: "EditClient",
			Handler:    _ControlHome_EditClient_Handler,
		},
		{
			MethodName: "AddClientPlace",
			Handler:    _ControlHome_AddClientPlace_Handler,
		},
		{
			MethodName: "EditClientPlace",
			Handler:    _ControlHome_EditClientPlace_Handler,
		},
		{
			MethodName: "AddClientRoom",
			Handler:    _ControlHome_AddClientRoom_Handler,
		},
		{
			MethodName: "EditClientRoom",
			Handler:    _ControlHome_EditClientRoom_Handler,
		},
		{
			MethodName: "AddClientPortion",
			Handler:    _ControlHome_AddClientPortion_Handler,
		},
		{
			MethodName: "EditClientPortion",
			Handler:    _ControlHome_EditClientPortion_Handler,
		},
		{
			MethodName: "AddClientAppliance",
			Handler:    _ControlHome_AddClientAppliance_Handler,
		},
		{
			MethodName: "EditClientAppliance",
			Handler:    _ControlHome_EditClientAppliance_Handler,
		},
		{
			MethodName: "ControlAppliance",
			Handler:    _ControlHome_ControlAppliance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/services.proto",
}

func init() { proto.RegisterFile("services/services.proto", fileDescriptor_services_6f6bc4c5b9569fc9) }

var fileDescriptor_services_6f6bc4c5b9569fc9 = []byte{
	// 1180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x86, 0x2c, 0xff, 0x1e, 0xbb, 0x49, 0xc3, 0xa4, 0x89, 0xaa, 0x76, 0xa9, 0xca, 0xa6, 0x83,
	0xb7, 0x02, 0x1e, 0x92, 0x6c, 0xeb, 0xc5, 0x2e, 0x06, 0xc7, 0x2d, 0xb2, 0x02, 0x9b, 0x17, 0x28,
	0x43, 0x81, 0x15, 0x03, 0x0a, 0xc5, 0x26, 0x02, 0x03, 0xb2, 0xe5, 0x59, 0xf2, 0x72, 0xb1, 0x5d,
	0xee, 0xbe, 0xd7, 0x03, 0xb6, 0x8b, 0x3d, 0xc4, 0x1e, 0x61, 0x2f, 0xb0, 0x97, 0xd8, 0x6b, 0x0c,
	0x3c, 0xa2, 0x44, 0x52, 0x92, 0xad, 0x04, 0x59, 0xaf, 0xc2, 0x73, 0xf8, 0xf9, 0xf0, 0xfb, 0xc8,
	0xa3, 0x8f, 0x44, 0x60, 0x2f, 0x64, 0x8b, 0x9f, 0x26, 0x23, 0x16, 0x7e, 0x92, 0x0c, 0x7a, 0xf3,
	0x45, 0x10, 0x05, 0xa4, 0x99, 0xc4, 0xf4, 0x37, 0x13, 0x5a, 0xfd, 0xf9, 0xdc, 0x9f, 0x78, 0xb3,
	0x11, 0x23, 0x0e, 0xb4, 0xd3, 0xe0, 0xd5, 0x0b, 0xcb, 0x70, 0x8c, 0x6e, 0xcb, 0x55, 0x53, 0xe4,
	0x00, 0xee, 0xa4, 0xe1, 0xd0, 0x9b, 0x32, 0xab, 0x82, 0x18, 0x3d, 0x49, 0x3e, 0x84, 0x8d, 0x17,
	0x93, 0xcb, 0x49, 0xe4, 0xf9, 0x83, 0x60, 0x16, 0x2d, 0x02, 0xdf, 0x32, 0x1d, 0xa3, 0xdb, 0x74,
	0x33, 0x59, 0xd2, 0x85, 0xcd, 0xfe, 0xcc, 0xf3, 0x83, 0xcb, 0x25, 0x4b, 0x80, 0x55, 0x04, 0x66,
	0xd3, 0x84, 0x40, 0xf5, 0x3b, 0x36, 0x9d, 0x5b, 0x35, 0x9c, 0xc6, 0x31, 0xd9, 0x81, 0xda, 0x20,
	0xf0, 0x83, 0x85, 0x55, 0xc7, 0x64, 0x1c, 0x10, 0x0a, 0x1d, 0xb1, 0xca, 0x6b, 0xcf, 0x5f, 0x32,
	0xab, 0xe1, 0x18, 0xdd, 0x9a, 0xab, 0xe5, 0x50, 0x85, 0x58, 0x20, 0x06, 0x35, 0x11, 0xa4, 0x27,
	0x89, 0x0d, 0x4d, 0x2c, 0xe9, 0xb2, 0xb1, 0xd5, 0x42, 0x40, 0x1a, 0x93, 0x87, 0xd0, 0xc2, 0xf1,
	0x09, 0xff, 0x35, 0xe0, 0xa4, 0x4c, 0x90, 0x7d, 0x00, 0x0c, 0x4e, 0x17, 0x8c, 0xcd, 0xac, 0x36,
	0x4e, 0x2b, 0x19, 0xbe, 0x3e, 0x57, 0xf0, 0x6a, 0x36, 0x60, 0xfe, 0x68, 0xb2, 0x0c, 0xad, 0x4e,
	0xbc, 0xbe, 0x96, 0xa4, 0xef, 0x2a, 0xd0, 0x38, 0x0b, 0x16, 0xd1, 0x24, 0x98, 0xf1, 0xf5, 0xc4,
	0x30, 0x3d, 0x17, 0x99, 0xe0, 0xe7, 0x26, 0x02, 0xe5, 0x4c, 0xd4, 0x14, 0xdf, 0x69, 0x11, 0x7e,
	0x1d, 0x8c, 0x3c, 0xfe, 0x17, 0x8f, 0xa4, 0xe5, 0x66, 0xd3, 0x9c, 0x5b, 0x52, 0x78, 0xea, 0x5d,
	0xb2, 0xd0, 0xaa, 0x3a, 0x26, 0x3f, 0x61, 0x2d, 0x49, 0xfa, 0xb0, 0x25, 0x12, 0xe9, 0xc9, 0x87,
	0x56, 0xcd, 0x31, 0xbb, 0xed, 0xa3, 0xed, 0x5e, 0xda, 0x6d, 0xe9, 0x9c, 0x9b, 0x47, 0x93, 0x43,
	0x80, 0xf3, 0xe5, 0x85, 0xc8, 0x5b, 0x75, 0xfc, 0xed, 0x96, 0xfc, 0xad, 0x98, 0x70, 0x15, 0x10,
	0xfd, 0xd7, 0x80, 0xaa, 0x1b, 0x04, 0x53, 0xb2, 0x0b, 0x75, 0xfe, 0x37, 0xdd, 0x0b, 0x11, 0xf1,
	0x23, 0xe3, 0x23, 0x65, 0x17, 0xd2, 0x98, 0x37, 0x06, 0x1f, 0x67, 0xf4, 0x6b, 0x39, 0x7e, 0x70,
	0x58, 0x49, 0x55, 0xae, 0x64, 0xc8, 0x17, 0xb0, 0xc1, 0xa3, 0xeb, 0x69, 0xce, 0x40, 0xc9, 0xc7,
	0xd0, 0x3c, 0x5f, 0x5e, 0xf0, 0x64, 0x28, 0xe4, 0x6e, 0xc8, 0x9f, 0xf1, 0xb4, 0x9b, 0xce, 0xd3,
	0xbf, 0x0c, 0xa8, 0x9d, 0xf9, 0xde, 0x88, 0x11, 0x0b, 0x1a, 0x38, 0x48, 0xb5, 0x26, 0x21, 0xf6,
	0x04, 0x1f, 0x2a, 0x6a, 0x65, 0x82, 0xcb, 0xc5, 0xa0, 0x3f, 0x1e, 0x2f, 0x58, 0x18, 0x26, 0x72,
	0xd5, 0x1c, 0xf6, 0x0d, 0x16, 0x53, 0xf5, 0xaa, 0x29, 0xd2, 0x03, 0xc0, 0x30, 0x66, 0x5d, 0x2b,
	0x64, 0xad, 0x20, 0xf8, 0x09, 0xd5, 0x07, 0xfe, 0x84, 0xcd, 0x22, 0xfc, 0x7c, 0x70, 0x94, 0x32,
	0x4f, 0x63, 0xfc, 0x40, 0x70, 0xac, 0x70, 0x57, 0x32, 0xbc, 0x09, 0xe3, 0x48, 0x67, 0xaf, 0x27,
	0x25, 0x8a, 0xbb, 0x84, 0x37, 0x8a, 0xd0, 0x3c, 0x4c, 0x57, 0x4f, 0x72, 0x91, 0x71, 0xe2, 0xe5,
	0xd4, 0x9b, 0xf8, 0xe8, 0x20, 0x2d, 0x57, 0x4d, 0x91, 0x63, 0xe8, 0xc4, 0x21, 0x0a, 0x49, 0x0e,
	0x67, 0x53, 0xe9, 0x45, 0x14, 0xa8, 0x81, 0xe8, 0x97, 0xb0, 0x3d, 0x58, 0x30, 0x2f, 0x62, 0x71,
	0xd6, 0x65, 0x3f, 0x2e, 0x59, 0x18, 0x91, 0x6e, 0xa2, 0x1f, 0x35, 0xb7, 0x8f, 0xee, 0xca, 0x2a,
	0x02, 0x28, 0xe6, 0xe9, 0x1b, 0xd8, 0xd1, 0x0b, 0x84, 0xf3, 0x60, 0x16, 0xe2, 0x81, 0x9f, 0x2f,
	0x47, 0x23, 0xae, 0xda, 0x40, 0x63, 0x4b, 0x42, 0xa5, 0x76, 0xa5, 0xa4, 0xf6, 0xb7, 0xd0, 0x18,
	0x04, 0xd3, 0xa9, 0x37, 0x1b, 0x73, 0x97, 0x8c, 0x3d, 0xce, 0x40, 0x8f, 0xa9, 0x65, 0xbc, 0xed,
	0xf4, 0xc4, 0xaa, 0x38, 0xa6, 0xf4, 0xb6, 0xd3, 0x93, 0xd4, 0x6b, 0x4d, 0xfc, 0x01, 0x8e, 0xe9,
	0xaf, 0x06, 0xec, 0x09, 0x2f, 0x96, 0x0d, 0x2e, 0x24, 0xaf, 0x3b, 0xe8, 0xcc, 0x8d, 0x52, 0xc9,
	0xdf, 0x28, 0xcf, 0x52, 0xaa, 0xb8, 0xa0, 0xe6, 0x01, 0x62, 0xc2, 0x4d, 0x10, 0xf4, 0x0f, 0x03,
	0xac, 0x3c, 0x0d, 0xb1, 0x71, 0xb7, 0xe3, 0xa1, 0x6c, 0xbb, 0xa9, 0x6f, 0xfb, 0x47, 0x50, 0x77,
	0x59, 0xb8, 0xf4, 0xe3, 0xfe, 0x2a, 0x24, 0x28, 0x00, 0xf4, 0x2d, 0x6c, 0xbd, 0x1c, 0x4f, 0x22,
	0xbd, 0x25, 0xd6, 0xf1, 0xea, 0x41, 0x6b, 0xc8, 0xae, 0x4a, 0x4e, 0x55, 0x42, 0x68, 0x0f, 0x88,
	0xba, 0x40, 0x59, 0xcb, 0xd0, 0x37, 0x70, 0xaf, 0x3f, 0x1e, 0x2b, 0x8d, 0x7b, 0x1d, 0x52, 0x4f,
	0x85, 0xf7, 0x08, 0x42, 0xb9, 0x0f, 0x21, 0x9e, 0xa5, 0x47, 0xb0, 0x9b, 0xad, 0x5d, 0xca, 0xe7,
	0x67, 0xd8, 0x95, 0xfc, 0xaf, 0x4d, 0x48, 0xf1, 0xc0, 0x8a, 0xee, 0x81, 0xcf, 0xa0, 0x39, 0x64,
	0x57, 0x31, 0x5b, 0xb3, 0x98, 0x6d, 0x0a, 0xa0, 0xc7, 0xb0, 0x97, 0x5b, 0xbc, 0x94, 0xf1, 0x1c,
	0x76, 0x52, 0x95, 0x68, 0x77, 0xb7, 0xe2, 0x4b, 0xe3, 0x0b, 0x4c, 0x70, 0xcd, 0x3a, 0x29, 0xce,
	0xd1, 0x43, 0xe5, 0xcc, 0xe2, 0x15, 0x4b, 0x49, 0xbe, 0x33, 0xe0, 0x9e, 0xd2, 0x17, 0xb7, 0xa6,
	0x29, 0xef, 0x57, 0x53, 0xbb, 0x5f, 0xbb, 0xd0, 0x18, 0xb2, 0x2b, 0x54, 0x50, 0x2d, 0x54, 0x90,
	0x4c, 0xf3, 0xe6, 0xc8, 0x12, 0x2a, 0x55, 0xf1, 0xbb, 0x01, 0xf7, 0x53, 0xe5, 0x37, 0xb2, 0x99,
	0x9b, 0x2b, 0x39, 0x54, 0xde, 0xbd, 0x42, 0x4b, 0xe1, 0x25, 0x2e, 0x51, 0xf4, 0x73, 0xb0, 0x8b,
	0xd8, 0x95, 0xca, 0xfa, 0xdb, 0x00, 0x5b, 0xee, 0xc5, 0x7b, 0xd6, 0x95, 0x31, 0xba, 0x6a, 0xde,
	0xe8, 0x9e, 0x43, 0x67, 0xc8, 0xae, 0xa4, 0xf8, 0xda, 0x6a, 0xf1, 0x1a, 0x90, 0x3e, 0x87, 0x07,
	0x85, 0x32, 0x4a, 0x37, 0xe0, 0x17, 0xd8, 0x93, 0x46, 0x21, 0x9e, 0x75, 0xb7, 0xfc, 0xea, 0x93,
	0x87, 0x71, 0xfe, 0xce, 0x48, 0x16, 0x48, 0x10, 0xf4, 0x53, 0xb0, 0xf2, 0xab, 0x97, 0x72, 0xfe,
	0xd3, 0x00, 0x4b, 0x31, 0x8b, 0xff, 0x83, 0xb5, 0xf6, 0x86, 0x37, 0xb3, 0x6f, 0xf8, 0x43, 0x00,
	0x6e, 0x54, 0x42, 0x56, 0x75, 0x95, 0x2c, 0x05, 0x44, 0x3f, 0x83, 0xfb, 0x05, 0x14, 0xcb, 0xa4,
	0x1d, 0xfd, 0xd3, 0x80, 0xb6, 0xb8, 0x44, 0xbf, 0x0a, 0xa6, 0x8c, 0x7c, 0x03, 0x1d, 0xf5, 0x21,
	0x42, 0x3e, 0x50, 0x2e, 0xa0, 0xfc, 0x0b, 0xc7, 0xde, 0x5f, 0x35, 0x2d, 0x16, 0x3e, 0x05, 0x90,
	0xac, 0xc8, 0x03, 0x89, 0xce, 0xdd, 0x8c, 0xf6, 0xc3, 0xe2, 0x49, 0x51, 0xe8, 0x1c, 0x36, 0xf4,
	0xfb, 0x85, 0x3c, 0x52, 0x9a, 0xb4, 0xe8, 0x56, 0xb3, 0x9d, 0xd5, 0x00, 0x51, 0xf4, 0x35, 0x6c,
	0x66, 0xee, 0x00, 0xe2, 0x14, 0xb1, 0xd0, 0xca, 0x3e, 0x5e, 0x83, 0x10, 0x75, 0xcf, 0xe0, 0x8e,
	0x66, 0xda, 0x64, 0xbf, 0x80, 0x8a, 0x62, 0xcc, 0xf6, 0xa3, 0x95, 0xf3, 0x52, 0xbe, 0xee, 0xa0,
	0xaa, 0xfc, 0x42, 0xb3, 0xb7, 0x9d, 0xd5, 0x00, 0x51, 0xf4, 0x7b, 0xb8, 0x9b, 0xfd, 0x18, 0xc8,
	0xe3, 0xa2, 0x4d, 0xd3, 0x1a, 0xde, 0xa6, 0xeb, 0x20, 0xa2, 0xf4, 0x0f, 0xea, 0xdb, 0x27, 0xa9,
	0x4d, 0x0b, 0x77, 0x4e, 0x2f, 0xfe, 0x64, 0x2d, 0x46, 0x54, 0x7f, 0x0b, 0x24, 0x6f, 0xbe, 0xe4,
	0x49, 0x01, 0xaf, 0xac, 0xc1, 0xda, 0x07, 0xeb, 0x41, 0x62, 0x81, 0x0b, 0xd8, 0x2e, 0x70, 0x37,
	0x72, 0x50, 0x44, 0x2e, 0xb7, 0xc4, 0xd3, 0x12, 0x94, 0xdc, 0xfd, 0xec, 0xeb, 0x55, 0xdd, 0xfd,
	0x15, 0x0f, 0x6c, 0x75, 0xf7, 0x57, 0x3d, 0x7e, 0x2f, 0xea, 0xf8, 0x9f, 0x9d, 0xe3, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x01, 0x36, 0xc7, 0x20, 0xf4, 0x11, 0x00, 0x00,
}
